/*
 * Shared Mode 01 PID catalogue.
 *
 * Names and descriptions are derived from kierandrewett/obd. The firmware
 * uses the priority field for polling and the collector uses the same entries
 * for Prometheus labels. Define OBD_PID before including this file.
 */
#ifndef OBD_PID
#error "Define OBD_PID(pid, name, description, unit, priority) before including obd_pids.h"
#endif

OBD_PID(0x01, status_since_dtcs_cleared, "Status since DTCs cleared", "code", 3)
OBD_PID(0x02, freeze_frame_dtc, "DTC that triggered freeze frame", "code", 3)
OBD_PID(0x03, fuel_system_status, "Fuel system status", "code", 3)
OBD_PID(0x04, calculated_engine_load, "Calculated engine load", "percent", 1)
OBD_PID(0x05, engine_coolant_temperature, "Engine coolant temperature", "celsius", 2)
OBD_PID(0x06, short_term_fuel_trim_bank_1, "Short-term fuel trim bank 1", "percent", 2)
OBD_PID(0x07, long_term_fuel_trim_bank_1, "Long-term fuel trim bank 1", "percent", 2)
OBD_PID(0x08, short_term_fuel_trim_bank_2, "Short-term fuel trim bank 2", "percent", 2)
OBD_PID(0x09, long_term_fuel_trim_bank_2, "Long-term fuel trim bank 2", "percent", 2)
OBD_PID(0x0A, fuel_pressure, "Fuel pressure", "kilopascal", 2)
OBD_PID(0x0B, intake_manifold_pressure, "Intake manifold absolute pressure", "kilopascal", 2)
OBD_PID(0x0C, engine_rpm, "Engine speed", "rpm", 1)
OBD_PID(0x0D, vehicle_speed, "Vehicle speed", "kilometres_per_hour", 1)
OBD_PID(0x0E, timing_advance, "Timing advance", "degree", 2)
OBD_PID(0x0F, intake_air_temperature, "Intake air temperature", "celsius", 2)
OBD_PID(0x10, mass_air_flow, "Mass air flow rate", "grams_per_second", 2)
OBD_PID(0x11, throttle_position, "Throttle position", "percent", 1)
OBD_PID(0x12, secondary_air_status, "Commanded secondary air status", "code", 3)
OBD_PID(0x14, oxygen_sensor_b1s1_voltage, "Oxygen sensor bank 1 sensor 1 voltage", "volt", 2)
OBD_PID(0x15, oxygen_sensor_b1s2_voltage, "Oxygen sensor bank 1 sensor 2 voltage", "volt", 2)
OBD_PID(0x16, oxygen_sensor_b1s3_voltage, "Oxygen sensor bank 1 sensor 3 voltage", "volt", 2)
OBD_PID(0x17, oxygen_sensor_b1s4_voltage, "Oxygen sensor bank 1 sensor 4 voltage", "volt", 2)
OBD_PID(0x18, oxygen_sensor_b2s1_voltage, "Oxygen sensor bank 2 sensor 1 voltage", "volt", 2)
OBD_PID(0x19, oxygen_sensor_b2s2_voltage, "Oxygen sensor bank 2 sensor 2 voltage", "volt", 2)
OBD_PID(0x1A, oxygen_sensor_b2s3_voltage, "Oxygen sensor bank 2 sensor 3 voltage", "volt", 2)
OBD_PID(0x1B, oxygen_sensor_b2s4_voltage, "Oxygen sensor bank 2 sensor 4 voltage", "volt", 2)
OBD_PID(0x1C, obd_standard, "OBD standard compliance", "code", 3)
OBD_PID(0x1E, auxiliary_input_status, "Auxiliary input status", "boolean", 3)
OBD_PID(0x1F, engine_run_time, "Engine run time", "second", 3)
OBD_PID(0x21, distance_with_mil, "Distance travelled with MIL on", "kilometre", 3)
OBD_PID(0x22, fuel_rail_pressure_relative, "Fuel rail pressure relative to manifold vacuum", "kilopascal", 2)
OBD_PID(0x23, fuel_rail_pressure_direct, "Direct-injection fuel rail pressure", "megapascal", 2)
OBD_PID(0x24, oxygen_sensor_1_wide_voltage, "Wide-range oxygen sensor 1 voltage", "volt", 2)
OBD_PID(0x25, oxygen_sensor_2_wide_voltage, "Wide-range oxygen sensor 2 voltage", "volt", 2)
OBD_PID(0x26, oxygen_sensor_3_wide_voltage, "Wide-range oxygen sensor 3 voltage", "volt", 2)
OBD_PID(0x27, oxygen_sensor_4_wide_voltage, "Wide-range oxygen sensor 4 voltage", "volt", 2)
OBD_PID(0x28, oxygen_sensor_5_wide_voltage, "Wide-range oxygen sensor 5 voltage", "volt", 2)
OBD_PID(0x29, oxygen_sensor_6_wide_voltage, "Wide-range oxygen sensor 6 voltage", "volt", 2)
OBD_PID(0x2A, oxygen_sensor_7_wide_voltage, "Wide-range oxygen sensor 7 voltage", "volt", 2)
OBD_PID(0x2B, oxygen_sensor_8_wide_voltage, "Wide-range oxygen sensor 8 voltage", "volt", 2)
OBD_PID(0x2C, commanded_egr, "Commanded EGR", "percent", 2)
OBD_PID(0x2D, egr_error, "EGR error", "percent", 2)
OBD_PID(0x2E, commanded_evaporative_purge, "Commanded evaporative purge", "percent", 2)
OBD_PID(0x2F, fuel_level, "Fuel tank level input", "percent", 2)
OBD_PID(0x30, warmups_since_dtcs_cleared, "Warm-ups since DTCs cleared", "count", 3)
OBD_PID(0x31, distance_since_dtcs_cleared, "Distance since DTCs cleared", "kilometre", 3)
OBD_PID(0x32, evaporative_system_vapour_pressure, "Evaporative system vapour pressure", "pascal", 2)
OBD_PID(0x33, barometric_pressure, "Absolute barometric pressure", "kilopascal", 2)
OBD_PID(0x34, oxygen_sensor_1_wide_current, "Wide-range oxygen sensor 1 current", "milliampere", 2)
OBD_PID(0x35, oxygen_sensor_2_wide_current, "Wide-range oxygen sensor 2 current", "milliampere", 2)
OBD_PID(0x36, oxygen_sensor_3_wide_current, "Wide-range oxygen sensor 3 current", "milliampere", 2)
OBD_PID(0x37, oxygen_sensor_4_wide_current, "Wide-range oxygen sensor 4 current", "milliampere", 2)
OBD_PID(0x38, oxygen_sensor_5_wide_current, "Wide-range oxygen sensor 5 current", "milliampere", 2)
OBD_PID(0x39, oxygen_sensor_6_wide_current, "Wide-range oxygen sensor 6 current", "milliampere", 2)
OBD_PID(0x3A, oxygen_sensor_7_wide_current, "Wide-range oxygen sensor 7 current", "milliampere", 2)
OBD_PID(0x3B, oxygen_sensor_8_wide_current, "Wide-range oxygen sensor 8 current", "milliampere", 2)
OBD_PID(0x3C, catalyst_temperature_b1s1, "Catalyst temperature bank 1 sensor 1", "celsius", 2)
OBD_PID(0x3D, catalyst_temperature_b2s1, "Catalyst temperature bank 2 sensor 1", "celsius", 2)
OBD_PID(0x3E, catalyst_temperature_b1s2, "Catalyst temperature bank 1 sensor 2", "celsius", 2)
OBD_PID(0x3F, catalyst_temperature_b2s2, "Catalyst temperature bank 2 sensor 2", "celsius", 2)
OBD_PID(0x42, control_module_voltage, "Control module voltage", "volt", 2)
OBD_PID(0x43, absolute_engine_load, "Absolute engine load", "percent", 2)
OBD_PID(0x44, commanded_equivalence_ratio, "Commanded air-fuel equivalence ratio", "ratio", 2)
OBD_PID(0x45, relative_throttle_position, "Relative throttle position", "percent", 2)
OBD_PID(0x46, ambient_air_temperature, "Ambient air temperature", "celsius", 2)
OBD_PID(0x47, absolute_throttle_position_b, "Absolute throttle position B", "percent", 2)
OBD_PID(0x48, absolute_throttle_position_c, "Absolute throttle position C", "percent", 2)
OBD_PID(0x49, accelerator_pedal_position_d, "Accelerator pedal position D", "percent", 2)
OBD_PID(0x4A, accelerator_pedal_position_e, "Accelerator pedal position E", "percent", 2)
OBD_PID(0x4B, accelerator_pedal_position_f, "Accelerator pedal position F", "percent", 2)
OBD_PID(0x4C, commanded_throttle_actuator, "Commanded throttle actuator", "percent", 2)
OBD_PID(0x4D, time_with_mil, "Time run with MIL on", "minute", 3)
OBD_PID(0x4E, time_since_dtcs_cleared, "Time since DTCs cleared", "minute", 3)
OBD_PID(0x51, fuel_type, "Fuel type", "code", 3)
OBD_PID(0x52, ethanol_fuel_percentage, "Ethanol fuel percentage", "percent", 2)
OBD_PID(0x53, absolute_evaporative_system_vapour_pressure, "Absolute evaporative system vapour pressure", "kilopascal", 2)
OBD_PID(0x54, evaporative_system_vapour_pressure_alt, "Evaporative system vapour pressure", "pascal", 2)
OBD_PID(0x59, absolute_fuel_rail_pressure, "Absolute fuel rail pressure", "kilopascal", 2)
OBD_PID(0x5A, relative_accelerator_pedal_position, "Relative accelerator pedal position", "percent", 2)
OBD_PID(0x5B, hybrid_battery_remaining_life, "Hybrid battery pack remaining life", "percent", 2)
OBD_PID(0x5C, engine_oil_temperature, "Engine oil temperature", "celsius", 2)
OBD_PID(0x5D, fuel_injection_timing, "Fuel injection timing", "degree", 2)
OBD_PID(0x5E, engine_fuel_rate, "Engine fuel rate", "litres_per_hour", 2)
OBD_PID(0x61, driver_demand_engine_torque, "Driver demand engine torque", "percent", 2)
OBD_PID(0x62, actual_engine_torque, "Actual engine torque", "percent", 2)
OBD_PID(0x63, engine_reference_torque, "Engine reference torque", "newton_metre", 2)
OBD_PID(0xA6, odometer, "Vehicle odometer", "kilometre", 3)

#undef OBD_PID
